import type { Plan, WorkoutSession } from "@rpeak/domain";

export const DEMO_USER_ID = "demo-user";

const now = "2026-07-01T10:00:00.000Z";
const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60_000).toISOString();
const activeWorkoutStartedAt = minutesAgo(8);
const activeFirstSetStartedAt = minutesAgo(7);
const activeFirstSetCompletedAt = minutesAgo(6);

export const seedPlans: Plan[] = [
  {
    id: "demo-plan-fullbody",
    userId: DEMO_USER_ID,
    name: "Full body — Lunes",
    description: "Sesión de cuerpo completo, 3 series por ejercicio.",
    createdAt: now,
    updatedAt: now,
    blocks: [
      {
        type: "single",
        id: "block-squat",
        exercise: {
          id: "pe-squat",
          exerciseId: "barbell-squat",
          notes: "Calentar con barra vacía antes de la primera serie.",
          restBetweenSetsSec: 120,
          sets: [
            { id: "ps-1", kind: "reps", reps: { min: 6, max: 8 }, durationSec: null, weight: 60, targetRpe: 7 },
            { id: "ps-2", kind: "reps", reps: { min: 6, max: 8 }, durationSec: null, weight: 60, targetRpe: 8 },
            { id: "ps-3", kind: "reps", reps: { min: 6, max: 8 }, durationSec: null, weight: 60, targetRpe: 8.5 },
          ],
        },
      },
      {
        type: "single",
        id: "block-bench",
        exercise: {
          id: "pe-bench",
          exerciseId: "barbell-bench-press---medium-grip",
          notes: "",
          restBetweenSetsSec: 90,
          sets: [
            { id: "ps-4", kind: "reps", reps: { min: 8, max: 10 }, durationSec: null, weight: 40, targetRpe: 7 },
            { id: "ps-5", kind: "reps", reps: { min: 8, max: 10 }, durationSec: null, weight: 40, targetRpe: 8 },
            { id: "ps-6", kind: "reps", reps: { min: 8, max: 10 }, durationSec: null, weight: 40, targetRpe: null },
          ],
        },
      },
      {
        type: "single",
        id: "block-plank",
        exercise: {
          id: "pe-plank",
          exerciseId: "plank",
          notes: "Peso corporal.",
          restBetweenSetsSec: 45,
          sets: [
            { id: "ps-7", kind: "time", reps: null, durationSec: { min: 30, max: 45 }, weight: 0, targetRpe: null },
            { id: "ps-8", kind: "time", reps: null, durationSec: { min: 30, max: 45 }, weight: 0, targetRpe: null },
          ],
        },
      },
    ],
  },
  {
    id: "demo-plan-superset",
    userId: DEMO_USER_ID,
    name: "Empuje/Tirón — Superserie",
    description: "Superserie de press banca y remo con barra, 3 rondas.",
    createdAt: now,
    updatedAt: now,
    blocks: [
      {
        type: "superset",
        id: "block-superset-1",
        restBetweenExercisesSec: 20,
        restBetweenRoundsSec: 90,
        exercises: [
          {
            id: "pe-db-bench",
            exerciseId: "dumbbell-bench-press",
            notes: "",
            restBetweenSetsSec: 0,
            sets: [
              { id: "ps-9", kind: "reps", reps: { min: 10, max: 12 }, durationSec: null, weight: 16, targetRpe: 7 },
              { id: "ps-10", kind: "reps", reps: { min: 10, max: 12 }, durationSec: null, weight: 16, targetRpe: 7.5 },
              { id: "ps-11", kind: "reps", reps: { min: 10, max: 12 }, durationSec: null, weight: 16, targetRpe: 8 },
            ],
          },
          {
            id: "pe-row",
            exerciseId: "bent-over-barbell-row",
            notes: "",
            restBetweenSetsSec: 0,
            sets: [
              { id: "ps-12", kind: "reps", reps: { min: 10, max: 12 }, durationSec: null, weight: 30, targetRpe: 7 },
              { id: "ps-13", kind: "reps", reps: { min: 10, max: 12 }, durationSec: null, weight: 30, targetRpe: 7.5 },
              { id: "ps-14", kind: "reps", reps: { min: 10, max: 12 }, durationSec: null, weight: 30, targetRpe: 8 },
            ],
          },
        ],
      },
      {
        type: "single",
        id: "block-pullups",
        exercise: {
          id: "pe-pullups",
          exerciseId: "pullups",
          notes: "Asistencia con banda si hace falta.",
          restBetweenSetsSec: 90,
          sets: [
            { id: "ps-15", kind: "reps", reps: { min: 5, max: 8 }, durationSec: null, weight: 0, targetRpe: 8 },
            { id: "ps-16", kind: "reps", reps: { min: 5, max: 8 }, durationSec: null, weight: 0, targetRpe: 9 },
          ],
        },
      },
    ],
  },
];

export const seedWorkouts: WorkoutSession[] = [
  {
    id: "demo-workout-1",
    userId: DEMO_USER_ID,
    planId: "demo-plan-fullbody",
    name: "Full body — Lunes",
    notes: "Buena sesión, RPE algo alto en sentadilla.",
    startedAt: "2026-06-29T17:00:00.000Z",
    finishedAt: "2026-06-29T18:05:00.000Z",
    blocks: [
      {
        type: "single",
        id: "wb-squat",
        exercise: {
          id: "we-squat",
          planExerciseId: "pe-squat",
          exerciseId: "barbell-squat",
          notes: "",
          restBetweenSetsSec: 120,
          sets: [
            {
              id: "ws-1",
              planSetId: "ps-1",
              kind: "reps",
              targetReps: { min: 6, max: 8 },
              targetDurationSec: null,
              weight: 60,
              actualReps: 8,
              actualDurationSec: null,
              rpe: 7,
              completed: true,
              startedAt: "2026-06-29T17:00:00.000Z",
              completedAt: "2026-06-29T17:02:10.000Z",
            },
            {
              id: "ws-2",
              planSetId: "ps-2",
              kind: "reps",
              targetReps: { min: 6, max: 8 },
              targetDurationSec: null,
              weight: 60,
              actualReps: 7,
              actualDurationSec: null,
              rpe: 8,
              completed: true,
              startedAt: "2026-06-29T17:04:10.000Z",
              completedAt: "2026-06-29T17:06:20.000Z",
            },
            {
              id: "ws-3",
              planSetId: "ps-3",
              kind: "reps",
              targetReps: { min: 6, max: 8 },
              targetDurationSec: null,
              weight: 60,
              actualReps: 6,
              actualDurationSec: null,
              rpe: 9,
              completed: true,
              startedAt: "2026-06-29T17:08:20.000Z",
              completedAt: "2026-06-29T17:10:35.000Z",
            },
          ],
        },
      },
    ],
  },
  {
    id: "demo-workout-2",
    userId: DEMO_USER_ID,
    planId: "demo-plan-superset",
    name: "Empuje/Tirón — Superserie",
    notes: "",
    startedAt: activeWorkoutStartedAt,
    finishedAt: null,
    blocks: [
      {
        type: "superset",
        id: "wb-superset-1",
        restBetweenExercisesSec: 20,
        restBetweenRoundsSec: 90,
        exercises: [
          {
            id: "we-db-bench",
            planExerciseId: "pe-db-bench",
            exerciseId: "dumbbell-bench-press",
            notes: "",
            restBetweenSetsSec: 0,
            sets: [
              {
                id: "ws-4",
                planSetId: "ps-9",
                kind: "reps",
                targetReps: { min: 10, max: 12 },
                targetDurationSec: null,
                weight: 16,
                actualReps: 12,
                actualDurationSec: null,
                rpe: 7,
                completed: true,
                startedAt: activeFirstSetStartedAt,
                completedAt: activeFirstSetCompletedAt,
              },
              {
                id: "ws-5",
                planSetId: "ps-10",
                kind: "reps",
                targetReps: { min: 10, max: 12 },
                targetDurationSec: null,
                weight: 16,
                actualReps: null,
                actualDurationSec: null,
                rpe: null,
                completed: false,
                startedAt: null,
                completedAt: null,
              },
              {
                id: "ws-6",
                planSetId: "ps-11",
                kind: "reps",
                targetReps: { min: 10, max: 12 },
                targetDurationSec: null,
                weight: 16,
                actualReps: null,
                actualDurationSec: null,
                rpe: null,
                completed: false,
                startedAt: null,
                completedAt: null,
              },
            ],
          },
          {
            id: "we-row",
            planExerciseId: "pe-row",
            exerciseId: "bent-over-barbell-row",
            notes: "",
            restBetweenSetsSec: 0,
            sets: [
              {
                id: "ws-7",
                planSetId: "ps-12",
                kind: "reps",
                targetReps: { min: 10, max: 12 },
                targetDurationSec: null,
                weight: 30,
                actualReps: null,
                actualDurationSec: null,
                rpe: null,
                completed: false,
                startedAt: null,
                completedAt: null,
              },
              {
                id: "ws-8",
                planSetId: "ps-13",
                kind: "reps",
                targetReps: { min: 10, max: 12 },
                targetDurationSec: null,
                weight: 30,
                actualReps: null,
                actualDurationSec: null,
                rpe: null,
                completed: false,
                startedAt: null,
                completedAt: null,
              },
              {
                id: "ws-9",
                planSetId: "ps-14",
                kind: "reps",
                targetReps: { min: 10, max: 12 },
                targetDurationSec: null,
                weight: 30,
                actualReps: null,
                actualDurationSec: null,
                rpe: null,
                completed: false,
                startedAt: null,
                completedAt: null,
              },
            ],
          },
        ],
      },
      {
        type: "single",
        id: "wb-pullups",
        exercise: {
          id: "we-pullups",
          planExerciseId: "pe-pullups",
          exerciseId: "pullups",
          notes: "",
          restBetweenSetsSec: 90,
          sets: [
            {
              id: "ws-10",
              planSetId: "ps-15",
              kind: "reps",
              targetReps: { min: 5, max: 8 },
              targetDurationSec: null,
              weight: 0,
              actualReps: null,
              actualDurationSec: null,
              rpe: null,
              completed: false,
              startedAt: null,
              completedAt: null,
            },
            {
              id: "ws-11",
              planSetId: "ps-16",
              kind: "reps",
              targetReps: { min: 5, max: 8 },
              targetDurationSec: null,
              weight: 0,
              actualReps: null,
              actualDurationSec: null,
              rpe: null,
              completed: false,
              startedAt: null,
              completedAt: null,
            },
          ],
        },
      },
    ],
  },
];
